labels:
  metadata:
    color: "EEEEEE"
    description: Relates to package metadata

  trusty:
    color: "E95420"
    description: Ubuntu 14.04 Trusty Tahr LTS
  xenial:
    color: "E95420"
    description: Ubuntu 16.04 Xenial Xerus LTS
  bionic:
    color: "E95420"
    description: Ubuntu 18.04 Bionic Beaver LTS
  focal:
    color: "E95420"
    description: Ubuntu 20.04 Focal Fossa LTS
  jammy:
    color: "E95420"
    description: Ubuntu 22.04 Jammy Jellyfish LTS
  lunar:
    color: "E95420"
    description: Ubuntu 23.04 Lunar Lobster
  mantic:
    color: "E95420"
    description: Ubuntu 23.10 Mantic Minotaur
  noble:
    color: "E95420"
    description: Ubuntu 24.04 Noble Numbat LTS
  oracular:
    color: "E95420"
    description: Ubuntu 24.10 Oracular Oriole

  trusty-updates:
    color: "BD4319"
    description: Ubuntu 14.04 Trusty Tahr LTS Updates
  xenial-updates:
    color: "BD4319"
    description: Ubuntu 16.04 Xenial Xerus LTS Updates
  bionic-updates:
    color: "BD4319"
    description: Ubuntu 18.04 Bionic Beaver LTS Updates
  focal-updates:
    color: "BD4319"
    description: Ubuntu 20.04 Focal Fossa LTS Updates
  jammy-updates:
    color: "BD4319"
    description: Ubuntu 22.04 Jammy Jellyfish LTS Updates
  lunar-updates:
    color: "BD4319"
    description: Ubuntu 23.04 Lunar Lobster Updates
  mantic-updates:
    color: "BD4319"
    description: Ubuntu 23.10 Mantic Minotaur Updates
  noble-updates:
    color: "BD4319"
    description: Ubuntu 24.04 Noble Numbat LTS Updates
  oracular-updates:
    color: "BD4319"
    description: Ubuntu 24.10 Oracular Oriole Updates

  trusty-security:
    color: "F55720"
    description: Security Updates for Ubuntu 14.04 Trusty Tahr LTS
  xenial-security:
    color: "F55720"
    description: Security Updates for Ubuntu 16.04 Xenial Xerus LTS
  bionic-security:
    color: "F55720"
    description: Security Updates for Ubuntu 18.04 Bionic Beaver LTS
  focal-security:
    color: "F55720"
    description: Security Updates for Ubuntu 20.04 Focal Fossa LTS
  jammy-security:
    color: "F55720"
    description: Security Updates for Ubuntu 22.04 Jammy Jellyfish LTS
  lunar-security:
    color: "F55720"
    description: Security Updates for Ubuntu 23.04 Lunar Lobster
  mantic-security:
    color: "F55720"
    description: Security Updates for Ubuntu 23.10 Mantic Minotaur
  noble-security:
    color: "F55720"
    description: Security Updates for Ubuntu 24.04 Noble Numbat LTS
  oracular-security:
    color: "F55720"
    description: Security Updates for Ubuntu 24.10 Oracular Oriole
